# Generated by Django 3.1.2 on 2020-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=15)),
                ('specialist', models.CharField(max_length=20)),
                ('treatable_disease', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
