# Generated by Django 3.1.2 on 2020-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(max_length=30),
        ),
    ]
