# Generated by Django 3.1.2 on 2020-11-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201124_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='discription',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experience',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='treatable_disease',
            field=models.CharField(max_length=200),
        ),
    ]
