# Generated by Django 3.1.2 on 2020-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
