# Generated by Django 3.1.2 on 2020-11-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20201124_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patients',
        ),
    ]
