# Generated by Django 3.1.2 on 2020-11-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20201128_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='username',
        ),
    ]
