# Generated by Django 3.1.2 on 2020-12-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_patients_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('amounts', models.IntegerField()),
                ('comment', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
