# Generated by Django 3.1.4 on 2020-12-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_donator_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=800)),
            ],
        ),
    ]
