# Generated by Django 3.1.4 on 2020-12-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appointment_time',
        ),
    ]
