# Generated by Django 3.1.4 on 2020-12-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20201204_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('problem_start_date', models.DateField()),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=50)),
                ('issue', models.CharField(max_length=800)),
            ],
        ),
    ]
