# Generated by Django 3.1.2 on 2020-12-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20201205_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='user',
        ),
        migrations.AddField(
            model_name='user_type',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
