# Generated by Django 3.1.2 on 2020-12-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20201207_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_type',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
